name: Android CI (No-Local-Setup)

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build-debug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # Installa Gradle 8.7 anche se non hai il wrapper nel repo
      - name: Install Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # Genera il Gradle Wrapper dentro il repo di build (runtime)
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew clean assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: NotiAssist-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

  release:
    name: Build & Sign Release APK
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Install Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble Release (unsigned)
        run: ./gradlew clean assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Upload Release APK (signed)
        uses: actions/upload-artifact@v4
        with:
          name: NotiAssist-release-apk
          path: app/build/outputs/apk/release/*-signed.apk
          if-no-files-found: error

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
